// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi.Data;

#nullable disable

namespace webapi.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20240420085416_UpdateCreate7")]
    partial class UpdateCreate7
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("webapi.Models.DataDictionary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryCode")
                        .HasColumnType("INTEGER")
                        .HasComment("类别编码--有没有必须呢");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasComment("类别名称");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasComment("描述");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasComment("名称");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER")
                        .HasComment("值");

                    b.HasKey("Id");

                    b.ToTable("DataDictionary");
                });

            modelBuilder.Entity("webapi.Models.DrugInOutInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DrugId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER")
                        .HasComment("0(入库,增益),1(出库,报损),2(调拨)");

                    b.Property<int>("InOutQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InOutWay")
                        .HasColumnType("INTEGER")
                        .HasComment("进出库方式，入库方式具体看入库表，出库方式看出库表");

                    b.Property<int>("OriginalQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReceiptNo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("单据号");

                    b.HasKey("Id");

                    b.ToTable("DrugInOutInfo", t =>
                        {
                            t.HasComment("入库出库调拨记录");
                        });
                });

            modelBuilder.Entity("webapi.Models.DrugSendBatchOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BatchNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("DrugId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER")
                        .HasComment("入库,出库,调拨，增益，报损");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReceiptNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DrugSendBatchOrder", t =>
                        {
                            t.HasComment("执行批次顺序表");
                        });
                });

            modelBuilder.Entity("webapi.Models.DrugStockIn", b =>
                {
                    b.Property<int>("StockInId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasComment("入库自增长id编号");

                    b.Property<string>("Approver")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasComment("审核人");

                    b.Property<int>("ApproverId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Checker")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasComment("验收人");

                    b.Property<int>("CheckerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasComment("创建人");

                    b.Property<int>("CreatorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InWay")
                        .HasColumnType("INTEGER")
                        .HasComment("入库方式");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("制造商--这个只需要名字就行了");

                    b.Property<string>("ReceiptNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasComment("单据号");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("备注");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasComment("0草稿，1提交，审核");

                    b.Property<string>("StockInNo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("入库编号-生成的编号");

                    b.Property<string>("WarehoueName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("库房名称");

                    b.Property<int>("WarehoueNo")
                        .HasColumnType("INTEGER")
                        .HasComment("库房编号");

                    b.HasKey("StockInId");

                    b.ToTable("DrugStockIn", t =>
                        {
                            t.HasComment("药品入库");
                        });
                });

            modelBuilder.Entity("webapi.Models.DrugStockInDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BatchNo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("批次号");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("DrugId")
                        .HasColumnType("INTEGER")
                        .HasComment("药品编号");

                    b.Property<string>("DrugName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("药品名称");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("TEXT")
                        .HasComment("有效期");

                    b.Property<int>("InQuantity")
                        .HasColumnType("INTEGER")
                        .HasComment("入库数量");

                    b.Property<int>("InputQuantity")
                        .HasColumnType("INTEGER")
                        .HasComment("输入数量");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("TEXT")
                        .HasComment("采购单价");

                    b.Property<string>("ReceiptNo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("单据号");

                    b.Property<string>("StockInNo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("入库编号");

                    b.Property<int>("UnitType")
                        .HasColumnType("INTEGER")
                        .HasComment("入库单位类别，0包装单位，1零售单位");

                    b.HasKey("Id");

                    b.ToTable("DrugStockInDetail", t =>
                        {
                            t.HasComment("药品入库明细");
                        });
                });

            modelBuilder.Entity("webapi.Models.DrugStockOut", b =>
                {
                    b.Property<int>("StockOutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasComment("出库主键");

                    b.Property<string>("Approver")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasComment("审核人");

                    b.Property<int>("ApproverId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Checker")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasComment("验收人");

                    b.Property<int>("CheckerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasComment("创建人");

                    b.Property<int>("CreatorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OutWay")
                        .HasColumnType("INTEGER")
                        .HasComment("出库方式");

                    b.Property<string>("ReceiptNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasComment("单据号");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("备注");

                    b.Property<int>("StockOutNo")
                        .HasColumnType("INTEGER")
                        .HasComment("出库编号");

                    b.Property<string>("StockOutType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("出库类别");

                    b.Property<string>("WarehoueName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("库房名称");

                    b.Property<string>("WarehoueNo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("库房编号");

                    b.HasKey("StockOutId");

                    b.ToTable("DrugStockOut", t =>
                        {
                            t.HasComment("药品出库");
                        });
                });

            modelBuilder.Entity("webapi.Models.DrugStockOutDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("DrugId")
                        .HasColumnType("INTEGER")
                        .HasComment("药品编号");

                    b.Property<int>("InQuantity")
                        .HasColumnType("INTEGER")
                        .HasComment("入库数量");

                    b.Property<string>("ReceiptNo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("单据号");

                    b.Property<decimal>("StockOutAmount")
                        .HasColumnType("TEXT")
                        .HasComment("出库金额");

                    b.Property<int>("StockOutId")
                        .HasColumnType("INTEGER")
                        .HasComment("单据号");

                    b.HasKey("Id");

                    b.ToTable("DrugStockOutDetail", t =>
                        {
                            t.HasComment("药品出库明细");
                        });
                });

            modelBuilder.Entity("webapi.Models.DrugTransfer", b =>
                {
                    b.Property<int>("TransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Approver")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasComment("审核人");

                    b.Property<int>("ApproverId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Checker")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasComment("验收人");

                    b.Property<int>("CheckerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasComment("创建人");

                    b.Property<int>("CreatorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InWarehourseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InWarehourseNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutWarehouseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OutWarehouseNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReceiptNo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("单据号");

                    b.HasKey("TransferId");

                    b.ToTable("DrugTransfer", t =>
                        {
                            t.HasComment("药品调拨");
                        });
                });

            modelBuilder.Entity("webapi.Models.DrugTransferDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("DrugId")
                        .HasColumnType("INTEGER")
                        .HasComment("药品编号");

                    b.Property<string>("ReceiptNo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("单据号");

                    b.Property<int>("TransferId")
                        .HasColumnType("INTEGER")
                        .HasComment("单据号");

                    b.Property<int>("TransferQuantity")
                        .HasColumnType("INTEGER")
                        .HasComment("入库数量");

                    b.HasKey("Id");

                    b.ToTable("DrugTransferDetail", t =>
                        {
                            t.HasComment("药品调拨明细");
                        });
                });

            modelBuilder.Entity("webapi.Models.DrugWarehouse", b =>
                {
                    b.Property<int>("StockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("DrugId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DrugName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NeedSendQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StockNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WarehouseNo")
                        .HasColumnType("INTEGER");

                    b.HasKey("StockId");

                    b.ToTable("DrugWarehouse");
                });

            modelBuilder.Entity("webapi.Models.DrugWarehouseDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BatchNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("DrugId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StockNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WarehoseNo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DrugWarehouseDetail");
                });

            modelBuilder.Entity("webapi.Models.Drugs", b =>
                {
                    b.Property<int>("DrugId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApprovalNumber")
                        .HasColumnType("TEXT")
                        .HasComment("批准文号");

                    b.Property<int>("C2PQuantity")
                        .HasColumnType("INTEGER")
                        .HasComment("临床到包装单位的转换");

                    b.Property<decimal>("ClinicalPrice")
                        .HasPrecision(16, 4)
                        .HasColumnType("TEXT")
                        .HasComment("临床销售单价");

                    b.Property<int>("ClinicalSaleUnit")
                        .HasColumnType("INTEGER")
                        .HasComment("临床销售单位");

                    b.Property<string>("ClinicalUnit")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("临床单位");

                    b.Property<int>("DefaultSaleUnit")
                        .HasColumnType("INTEGER")
                        .HasComment("销售单位");

                    b.Property<string>("DosageForm")
                        .HasColumnType("TEXT")
                        .HasComment("药品剂型");

                    b.Property<string>("DrugCode")
                        .HasColumnType("TEXT")
                        .HasComment("本地药品编码");

                    b.Property<string>("DrugName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasComment("药品名称");

                    b.Property<string>("DrugType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("药品类别，0表示中药，1表示西药");

                    b.Property<string>("NationDrugCode")
                        .HasColumnType("TEXT")
                        .HasComment("国家药品编码");

                    b.Property<decimal>("PackagePrice")
                        .HasPrecision(16, 4)
                        .HasColumnType("TEXT")
                        .HasComment("包装单位销售单价");

                    b.Property<string>("PackageUnit")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("包装单位");

                    b.Property<string>("PinYin")
                        .HasColumnType("TEXT")
                        .HasComment("拼音码");

                    b.Property<string>("RADManufacturer")
                        .HasColumnType("TEXT")
                        .HasComment("药品研发厂家");

                    b.Property<int>("Sort")
                        .HasColumnType("INTEGER")
                        .HasComment("排序编号");

                    b.Property<string>("Spec")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("药品规格");

                    b.HasKey("DrugId");

                    b.ToTable("Drugs");
                });

            modelBuilder.Entity("webapi.Models.HierarchyDictionary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasComment("类别名称");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasComment("备注");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasComment("名称");

                    b.Property<int>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER")
                        .HasComment("值");

                    b.HasKey("Id");

                    b.ToTable("HierachyDictionary");
                });

            modelBuilder.Entity("webapi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
